---
    name: Lint
    on: # yamllint disable-line rule:truthy
        - push
    jobs:
        lint-test:
            name: Lint
            runs-on: ubuntu-latest
            steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '21'
            - name: Install
              run: npm ci
            - name: ESLint
              run: npm run lint